### PR TITLE
Add Tests

### PR DESCRIPTION
**Pull request by boldtrn**
This PR allows to test the MapboxResourceConverter. Currently there are no tests for the Resources (server side).

The test starts a GraphHopper instance and calculates routes. It uses the andorra.osm.gz that is also used in GraphHopper.

BTW: I also added a travis.yml. I am not sure if it works. Maybe @karussell you could try to enable travis after merging this PR. We also probably need to setup a secure notification email, etc.

### CODE REVIEW

**Comment by karussell** [comment]
Have done this in the new branch: https://travis-ci.org/graphhopper/graphhopper-navigation/builds/418730365

Feel free to merge both and tag the first release that is then publish on maven central. Maybe use a similar version for pre-releases (`<version>-pre-<x>`) like we currently do for graphhopper: https://github.com/graphhopper/graphhopper/releases

**Comment by boldtrn** [comment]
Thanks! I will use the same release tags like we do in gh :)

**Comment by karussell** [comment]
:+1: 

It might be the case that something does not work (as the setup was really easy compared to the hours I wasted on GH core, but maybe this was because of just copy&paste :)). So if you like release a pre-release even if it is broken :)

**Comment by boldtrn** [comment]
> So if you like release a pre-release even if it is broken :)

Thanks, I tried to release release a version. But I think I must have done something wrong.

What I did:
git tag
git push

The travis build was triggered again, with the tag. [But somehow the release did not start](https://travis-ci.org/graphhopper/graphhopper-navigation/jobs/419096149). Is there anything to watch out for?

**Comment by karussell** [comment]
If you click on the small triangle you see that the release process was started but it failed with:

```
gpg: gpg-agent is not available in this session
gpg: Sorry, no terminal at all requested - can't get input
...
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.6:sign (sign-artifacts) on project graphhopper-navigation: Exit code: 2 -> [Help 1]
```

**Comment by karussell** [comment]
Ok, there were a couple of secure variables missing: CI_DEPLOY_PASSWORD, CI_DEPLOY_USERNAME and GPG_PASSPHRASE.

Have triggered the build again.

**Comment by boldtrn** [comment]
Thanks!

It still seems to fail, but the error message changed :).

```
gpg: no default secret key: bad passphrase
gpg: signing failed: bad passphrase
```

**Comment by karussell** [comment]
This is good as its some progress ;)

I told you I've messed a long time with it, so now I'm documenting what is necessary.

**Comment by karussell** [comment]
Ok, deploying from local machine works with some minor changes but I have no idea why it fails with travis at the moment :(

**Comment by karussell** [comment]
The problem was that I used the email as an identifier to export the secret key but as I had a sub key I needed to be more specific ([using the key ID](https://github.com/graphhopper/graphhopper/commit/d7396f9c7f1400dc28fd1059c28d26ecbc1a26c1))

Please go ahead and tag the latest commit with pre2 or something and it should work.

**Comment by boldtrn** [comment]
Thanks, I just released a version on sonatype: https://oss.sonatype.org/content/groups/public/com/graphhopper/graphhopper-navigation-mapbox/0.11.0-pre1/

**Comment by karussell** [comment]
Nice! It should be available on maven central too (after ~20min, the maven search can take a bit longer though)

**Pull request merged**
